# https://golangci-lint.run/usage/quick-start/
run:
  timeout: 1m
  build-tags:
linters:
# https://golangci-lint.run/usage/linters/

  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    #- dogsled
    - durationcheck
    - dupword
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - grouper
    - importas
    - interfacebloat
    - lll
    - makezero
    - misspell
    - nakedret
    #- nestif
    #- nilerr
    - nlreturn
    - nolintlint
    - nonamedreturns
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - stylecheck
    - tagliatelle
    - tenv
    - unconvert
    - unparam
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck

linters-settings:
    lll:
      line-length: 160
issues:
  exclude-rules:
  exclude-files:
